# Generated by Django 3.0.4 on 2022-02-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='sid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
