# Generated by Django 3.0.4 on 2022-02-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220221_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
