# Generated by Django 3.0.4 on 2022-02-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220221_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='login_time',
            field=models.CharField(max_length=255),
        ),
    ]
